services:
  app_payglobal:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - main_network
    environment:
      DB_URL: jdbc:postgresql://vps-5600697-x.dattaweb.com/db_payglobal
      DB_USER_NAME: superUsuario
      DB_PASSWORD: P4ygl0b41+
      TZ: Etc/GMT+6
    restart: always

  frontend:
    build:
      context: frontend/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app_payglobal
    volumes:
      - ./frontend/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - VITE_API_BASE_URL=https://payglobal.vip/api
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
